mymoreapp/firstapp/urls.py
from django.urls import path,re_path
from .views import *
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('',index,name='firstpage'),
    re_path('delete/(\d+)/',del_record,name='delete'),
    re_path('edit/(\d+)/',edit_record,name='edit')
   
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mymoreapp/mymoreapp/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('firstapp.urls','firstapp'),namespace='app1')),
    path('app2/',include(('secondapp.urls','secondapp'),namespace='app2')),
]

mymoreapp/secondapp/urls.py
from django.urls import path
from .views import *



urlpatterns = [
    #127.0.0.1:8000/app2/
    path('home/', page2,name='second_page'),
   
]

mymoreapp/firstapp/models.py
from distutils.command.upload import upload
from django.db import models

# Create your models here.
class student(models.Model):
    name = models.CharField(max_length=10)
    course = models.CharField(max_length=15)
    email = models.EmailField()
    image = models.FileField(null=True,upload_to='pic')
    def __str__(self):
        return self.name

mymoreapp/secondapp/models.py
from django.db import models

# Create your models here.

mymoreapp/firstapp/views.py
from django.shortcuts import redirect, render
from .models import *
from secondapp.form import *

def index(request):
    data=student.objects.all()
    return render(request,'f1.html',{'data':data})


# To delete record
def del_record(request,d):
    s1=student.objects.get(id=d)
    s1.delete()
    return redirect('app1:firstpage')

#to edit data
def edit_record(request,d):
    s1 = student.objects.get(id=d)
    if request.method=='POST':
        #to submit the data and display
        form=student_form(request.POST,instance=s1)
        if form.is_valid():
            form.save()
            return redirect('app1:firstpage')
    else:
        form = student_form(instance=s1)
    

    return render(request,'edit.html',{'form':form})

mymoreapp/secondapp/views.py
from django.shortcuts import render,redirect
from secondapp.form import student_form

def page2(request):
    if request.method=='POST':
        #to submit the data and display
        form=student_form(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('app1:firstpage')
    else:
        form = student_form()
    

    return render(request,'home.html',{'form':form})
# Create your views here.

mymoreapp/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=h1, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>edit record</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="submit" >
    </form>
    <br>
    <a href="{% url 'app1:firstpage' %}">Click here for first page</a>
</body>
</html>

mymoreapp/templates/f1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=h1, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello...!| My first Page</h1>
    <h3>FETCH ALL STUDENTS DETAILS</h2>
    {% for i in data %}
    {% if i.image %}
    <h4>Student Image:</h4>
        <img src="{{i.image.url}}" width="500px" height="100px" >
    {% endif %}
    <p>Name:{{i.name}}</p><br>
    <p>course:{{i.course}}</p><br>
    <p>Email:{{i.email}}</p><br>
    <a href="{% url 'app1:delete' i.id %}">Delete</a>
    <a href="{% url 'app1:edit' i.id %}">edit</a>
    <hr>
    {% endfor %}
  

    <a href="{% url 'app2:second_page' %}">Click here for second app</a>
</body>
</html>

mymoreapp/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=h1, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Add student Record</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="submit" >
    </form>
    <br>
    <a href="{% url 'app1:firstpage' %}">Click here for first page</a>
</body>
</html>